{% set name = "centerline" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/centerline-{{ version }}.tar.gz
  sha256: a7d804a2acbac32f837c3ba60ae3d433eb68d9f1f2cbb7d9614a99fabe500e2e

build:
  entry_points:
    - create_centerlines = centerline.converters:create_centerlines
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - certifi
    - click >=7.0
    - fiona >=1.7.0
    - numpy >=1.10.4
    - python >={{ python_min }}
    - scipy >=0.16.1
    - shapely >=1.5.13

test:
  imports:
    - centerline
  commands:
    - pip check
    - create_centerlines --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fitodic/centerline
  summary: Calculate the centerline of a polygon
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
